function addControlSubsystem(modelName, p)
%ADDCONTROLSUBSYSTEM Synchronous-reference-frame control of the converter.
%
%   Phase-locked loop on the point of common coupling, proportional-integral
%   current control in the dq frame, decoupling with the FILTER inductance and
%   feed-forward of the measured voltage, then a transport delay representing
%   sampling, computation and modulation.
%
%   The decoupling inductance and the delay are the two choices that decide
%   whether a weak-grid study is meaningful; both are stated in
%   mali.inverterParameters and both are mirrored in the Python reference.

    control = [modelName '/Control'];
    add_block('simulink/Ports & Subsystems/Subsystem', control, ...
        'Position', [340 360 460 460]);
    delete_line(control, 'In1/1', 'Out1/1');

    inner = @(name) [control '/' name];

    add_block('powerlib/Control & Measurements/PLL/PLL (3ph)', inner('PLL'), ...
        'Position', [60 40 140 100]);
    set_param(inner('PLL'), 'Kp', num2str(p.Kp_pll), 'Ki', num2str(p.Ki_pll), ...
        'Freq', num2str(p.fNom));

    add_block('powerlib/Control & Measurements/Measurements/abc_to_dq0 Transformation', ...
        inner('abc_to_dq_v'), 'Position', [200 20 280 80]);
    add_block('powerlib/Control & Measurements/Measurements/abc_to_dq0 Transformation', ...
        inner('abc_to_dq_i'), 'Position', [200 120 280 180]);

    % Current references from the power setpoints.
    add_block('simulink/Sources/Constant', inner('Pref'), ...
        'Position', [40 200 80 230], 'Value', num2str(p.Pset));
    add_block('simulink/Sources/Constant', inner('Qref'), ...
        'Position', [40 250 80 280], 'Value', num2str(p.Qset));

    add_block('simulink/Discrete/Discrete PID Controller', inner('Id_control'), ...
        'Position', [360 120 440 180]);
    set_param(inner('Id_control'), 'Controller', 'PI', ...
        'P', num2str(p.Kp_i), 'I', num2str(p.Ki_i), ...
        'SampleTime', num2str(p.controlDelay / 3), ...
        'LimitOutput', 'on', 'UpperSaturationLimit', '2', ...
        'LowerSaturationLimit', '-2', 'AntiWindupMode', 'clamping');

    add_block('simulink/Discrete/Discrete PID Controller', inner('Iq_control'), ...
        'Position', [360 200 440 260]);
    set_param(inner('Iq_control'), 'Controller', 'PI', ...
        'P', num2str(p.Kp_i), 'I', num2str(p.Ki_i), ...
        'SampleTime', num2str(p.controlDelay / 3), ...
        'LimitOutput', 'on', 'UpperSaturationLimit', '2', ...
        'LowerSaturationLimit', '-2', 'AntiWindupMode', 'clamping');

    % Decoupling: the controller knows its own filter, not the network.
    add_block('simulink/Math Operations/Gain', inner('Decouple_d'), ...
        'Position', [360 300 400 330], 'Gain', num2str(-p.wNom * p.Lf));
    add_block('simulink/Math Operations/Gain', inner('Decouple_q'), ...
        'Position', [360 350 400 380], 'Gain', num2str(p.wNom * p.Lf));

    % Current limit, applied to the vector rather than to each axis.
    add_block('simulink/Discontinuities/Saturation', inner('CurrentLimit'), ...
        'Position', [300 120 330 150], ...
        'UpperLimit', num2str(p.currentLimit), ...
        'LowerLimit', num2str(-p.currentLimit));

    % Sampling, computation and modulation delay.
    add_block('simulink/Continuous/Transport Delay', inner('ControlDelay'), ...
        'Position', [480 160 520 200], 'DelayTime', num2str(p.controlDelay));

    add_block('powerlib/Control & Measurements/Measurements/dq0_to_abc Transformation', ...
        inner('dq_to_abc'), 'Position', [560 140 640 220]);
end
